### ISSUE TITLE
Add tests for {load$: true} params when remove$ is executed

### ISSUE THREAD

**Issue by mirceaalexandru** [senecajs/seneca-store-test#23]

**Comment by mirceaalexandru** [comment]
I will do this, cannot assign to me for some reason

**Comment by paolochiodi** [comment]
You amy want to look into this PR https://github.com/rjrodger/seneca-store-test/pull/18 that already contains those tests

**Comment by mirceaalexandru** [comment]
It's OK, I just need it updated to latest specifications for stores and published so I use them for my tests.

**Comment by paolochiodi** [comment]
Yep, that PR should bring all tests up to the latest specs, but it's waiting review before getting merged

**Comment by paolochiodi** [comment]
Fixed in the merged PR: https://github.com/senecajs/seneca-store-test/pull/18
