### ISSUE TITLE
tests are not passing

### ISSUE THREAD

**Issue by mirceaalexandru** [senecajs/seneca-store-test#26]

**Comment by paolochiodi** [comment]
I noticed I had a couple of commits not pushed yet, and tests for me are passing.
With updated dependencies I get 4 lint failures, possibly due to changed rules in recent hapi style.

Which tests are failing for you?

**Comment by mirceaalexandru** [comment]
@paolochiodi Sorry for not adding proper description. 
I will check this again and let you know.

**Comment by mirceaalexandru** [comment]
Closing as cannot be reproduced
