### ISSUE TITLE
Not sure if this is a correct feature: "should not save modifications to entity after save completes"

### ISSUE THREAD

**Issue by mirceaalexandru** [senecajs/seneca-store-test#27]
```
      it('should not save modifications to entity after save completes', function (done) {
        var foo = si.make('foo')
        foo.p3 = [ 'a' ]
        foo.save$(verify(done, function (foo1) {
          assert.deepEqual(foo1.p3, [ 'a' ])
          // now that foo is in the database, modify the original data
          foo.p3.push('b')
          assert.deepEqual(foo1.p3, [ 'a' ])
        }))
      })
```

I think we should allow changing the object, is up to client of the store to change it or not. If change is required and after that another save$ is required, why do not let doing something like:

```
var foo = si.make('foo')
foo.p3 = [ 'a' ]
foo.save$(function (err, foo1) {
  // do something here
  foo1.p3.push('b')
  foo1.save$(function(err, foo2){...........})
})
```

**Comment by paolochiodi** [comment]
Exactly: it's up to the client to determine if the change is required and need to be stored.
This test guards that:
- changes to a previously stored object aren't persisted without a call to save$
- changes to a previously stored object (that haven't been saved) aren't propagated to other instances of the same "record" previously loaded (in this case as part of a previous save)
Note that we change foo and test foo1 hasn't changed
Changes to the object with save$ are allowed.

This test originates from https://github.com/senecajs/seneca-mem-store/issues/2 and https://github.com/senecajs/seneca-store-test/issues/10
