### ISSUE TITLE
add github actions build

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca-store-test#66]
Example: https://github.com/senecajs/seneca-entity-depend/blob/main/.github/workflows/build.yml

**Comment by rjrodger** [comment]
Also add github build badge as per: https://github.com/senecajs/seneca-entity-depend/blob/main/README.md

**Comment by lilsweetcaligula** [comment]
@rjrodger Cannot access the specified links. Please advise.

**Comment by rjrodger** [comment]
repo was private - changed to public!
