### ISSUE TITLE
Reorganize test cases and names for easier eye-balling of cases

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca-store-test#71]
Separate into named functions and list linearly at top of test files

create branch for move to @seneca/store-test for this

**Comment by rjrodger** [comment]
just two levels needed as per the other tests

**Comment by lilsweetcaligula** [comment]
@rjrodger How do we go about cases where deeper nesting is required? Like, for example, we are testing a `#load$` method and there is a set of scenarios involving the method that we want to test separately. For each scenario there may be a set of subscenarios, and so on.

For example:
```
load$
  with id
    id is a string
    id is null
    id is a field in a query
  without id
```

**Comment by rjrodger** [comment]
upgrading this to a release requirement
the upsert tests are too difficult to follow in the current format

instead of deeper nesting, use utility functions, or just cut and paste the setup code
see the existing test as an example
