### ISSUE TITLE
Fix a mysterious bug

### ISSUE THREAD

**Issue by lilsweetcaligula** [senecajs/seneca-store-test#78]
While I was working on the `seneca-sqlite-store`, I stumbled upon a very interesting bug. Below I present the debug statements that help explain the problem:
```javascript
// lib/sqlite-store.js
    save: function (args, done) {
      console.dir(args.ent, { depth: 4 }) // debug output
```
```javascript
// node_modules/seneca-store-test/store-test.js
    describe('happy path', () => {
      it('is happy', async (fin) => {
        const foo_ent = si.entity('foo')
        const f01 = await foo_ent.data$({ x: 1, y: 22 }).save$()
        const f02 = await foo_ent.data$({ x: 2, y: 33 }).save$()
```
Running the 'happy path' test against the sqlite-store then produces the following output:
```
Output:
Entity { 'entity$': '-/-/foo', x: 1, y: 22 }
Entity {
  'entity$': '-/-/foo',
  x: 2,
  y: 33,
  id: '83e504c0-c72c-40f2-9af9-9214847d86cc'
}
```

That `id` field should really not be there. With equivalent debug statements in place in `seneca-mongo-store`, below is the output of the 'happy path' test:
```
Entity { 'entity$': '-/-/foo', x: 1, y: 22 }
Entity { 'entity$': '-/-/foo', x: 2, y: 33 }
```

The `seneca-postgres-store` also works fine on my `fix-tests` branch:
```
Entity { 'entity$': '-/-/foo', x: 1, y: 22 }
Entity { 'entity$': '-/-/foo', x: 2, y: 33 }
```

This may be related to the `Seneca#entity` method and/or the `seneca-promisify` package.

**Comment by rjrodger** [comment]
construct a plain old script (not a test) in the test folder of sqlite-store that reproduces this issue
Use that to find the root cause

**Comment by lilsweetcaligula** [comment]
https://github.com/senecajs-labs/seneca-sqlite-store/pull/34
